In [201]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

**NumPy Array** Numpy คือชื่อของ library ที่ใช้ในการคำนวนทางคณิตศาสตร์ มีความสามารถในการจัดการกับอาเรย์หลายมิติและข้อมูลแบบเมทริกซ์

ใช้คำสั่ง import เข้ามาแล้วตั้งชื่อว่า np

In [202]:
import numpy as np

ถ้าไม่มีคำสั่งนั้นในเครื่อง ให้ใช้คำสั่ง

In [203]:
!pip install numpy

เช็คเวอร์ชั่น

In [204]:
np.__version__

'1.19.5'

การรู้เวอร์ชั่นจำเป็นมาก เพราะในการวิเคราะห์ข้อมูลส่วนใหญ่จะอ้างอิงจากข้อมูลผู้อื่น หากเวอร์ชั่นไม่ตรงกันก็จะ error

Vector or 1D Array

In [205]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [206]:
a[0]

1

ช่วง index [_:_]

In [207]:
a[0:5]

array([1, 2, 3, 4, 5])

ก่อนถึง index ที่ _

In [208]:
a[8]

9

In [209]:
a[:8]

array([1, 2, 3, 4, 5, 6, 7, 8])

ตั้งแต่ index ที่ _

In [210]:
a[3]

4

In [211]:
a[3:] 

array([ 4,  5,  6,  7,  8,  9, 10])

นับ index ย้อนหลัง [-_]

In [212]:
a[-2]

9

In [213]:
a[2:-3]

array([3, 4, 5, 6, 7])

In [214]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [215]:
a[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [216]:
sorted(a, reverse=True)

[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

จำนวนสมาชิกใน array

In [217]:
np.size(a)

10

แสดงเวกเตอร์

In [218]:
np.shape(a)

(10,)

a[2] = 3
จะได้ a[3] = 4

In [219]:
a[a[2]]

4

Matrix or 2D Array

In [220]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [221]:
np.shape(b)

(3, 3)

ตำแหน่งแรกคือ row (เรียง0.1,2,...) ตำแหน่งสองคือ column (เรียง0,1,2,...)

In [222]:
b[1,2]

6

In [223]:
b[1,:]

array([4, 5, 6])

In [224]:
b[:,-1]

array([3, 6, 9])

เปลี่ยนค่าใน array (column)

In [225]:
b[:,-1]=0
b

array([[1, 2, 0],
       [4, 5, 0],
       [7, 8, 0]])

In [226]:
b[:,-1]=[3,6,9]
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

เปลี่ยนค่า array (row)

In [227]:
b[1,:]=0
b

array([[1, 2, 3],
       [0, 0, 0],
       [7, 8, 9]])

In [228]:
b[1,:]=[4,5,6]
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

เพิ่มข้อมูลใน array 3 มิติยังไง

In [229]:
b = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

จำนวนสมาชิกใน array

In [230]:
np.size(b)

12

In [231]:
np.size(b,0)

4

เช็คมิติของ array

In [232]:
np.ndim(b)

2

In [233]:
c = np.zeros((2, 3, 4))
c

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [234]:
np.ndim(c)

3

**Data is Matrix** ใน array ข้อมูลหลายรูปแบบ str,int

In [235]:
student = np.array ([[622110186,'น้ำผึ้ง'],[622110174,'กิ๊ฟ'],[622110150,'พลอย']])
student

array([['622110186', 'น้ำผึ้ง'],
       ['622110174', 'กิ๊ฟ'],
       ['622110150', 'พลอย']], dtype='<U21')

In [236]:
np.array(student[:,0],dtype = int)

array([622110186, 622110174, 622110150])

In [237]:
np.array(student[:,0])

array(['622110186', '622110174', '622110150'], dtype='<U21')

**Special Type of Matrix**

สร้าง matrix 2x2 ที่มีค่าทั้งหมดเป็น 0 และ 1

In [238]:
c = np.zeros((2,2))
c

array([[0., 0.],
       [0., 0.]])

In [239]:
d = np.ones((2,2))
d

array([[1., 1.],
       [1., 1.]])

สร้าง matrix ที่กำหนดค่าข้างในเหมือนกันทุกตัว

In [240]:
e = np.full((2,2),8)
e

array([[8, 8],
       [8, 8]])

เลขหน้าคือ row เลขหลังคือ column

In [241]:
f = np.full((2,4),14)
f

array([[14, 14, 14, 14],
       [14, 14, 14, 14]])

In [242]:
g = np.ones((5,5))*4
g

array([[4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.]])

สร้าง Identity matrix (เมทริกซ์เอกลักษณ์)

In [243]:
g = np.eye(2)
g

array([[1., 0.],
       [0., 1.]])

คูณเมทริกซ์แค่ที่ตำแแหน่งมันตรงกันแบบ 0,0 ของ e คูณ 0,0 ของ g

In [244]:
e*g

array([[8., 0.],
       [0., 8.]])

สั่งให้ matrix คูณกันแบบไม่ต้องตำแหน่งตรงกัน เพราะหากเมทริกซ์ใดๆคูณเมทริกซ์เอกลักษณ์จะได้ตัวมันเอง

In [245]:
np.matmul(e,g)

array([[8., 8.],
       [8., 8.]])

คูณจำนวนเข้าเมทริกซ์ได้เลย

In [246]:
4*np.ones((2,2))

array([[4., 4.],
       [4., 4.]])

รากที่ 2 ของเมทริกซ์ 2x2 เมื่อค่าข้างในเป็น 4

In [247]:
np.sqrt(np.full((2,2),4))

array([[2., 2.],
       [2., 2.]])

มันขยะที่อยูู่ใน array แค่จองพื้นที่ไว้ก่อน 

In [248]:
np.empty((5,5))

array([[4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.]])

In [249]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [250]:
def addone(a):
    return a+1
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

**Random**

สุ่มเลขระหว่าง 0-1

In [330]:
rng = np.random.RandomState(0)
rng.rand()

0.5488135039273248

สุ่มเลข 1-10

In [333]:
np.random.rand()*10

9.66686868252355

ถ้าทำ RandomState ไว้จะได้ค่าเดิมตลอด

In [350]:
rng.rand()*10

3.8344151882577773

In [335]:
rng = np.random.RandomState(0)
np.round(rng.rand()*10)

5.0

random ตั้งแต่ 0-4 

In [294]:
np.random.randint(5)

4

In [272]:
[np.round(np.random.rand()*10) for item in range(10)]

[9.0, 7.0, 4.0, 10.0, 6.0, 2.0, 10.0, 2.0, 5.0, 9.0]

ตั้งให้การสุ่มทุกครั้งสุ่มได้ค่าเดิม

In [327]:
random1 = np.random.RandomState(0)
np_matrix = random1.randint(3, size = (5,5))
np_matrix

array([[0, 1, 0, 1, 1],
       [2, 0, 2, 0, 0],
       [0, 2, 1, 2, 2],
       [0, 1, 1, 1, 1],
       [0, 1, 0, 0, 1]])

สุ่มมาให้ข้อมูลไม่ซ้ำกันใส่ replace = False

In [303]:
a = [1,2,3,4,5,6,7,8,9,10]
np.random.choice(a,5, replace=False)

array([10,  1,  3,  9,  8])

In [368]:
np_matrix = np.round(np.random.rand(5,5))
np_matrix

array([[1., 0., 0., 1., 1.],
       [0., 0., 0., 0., 1.],
       [1., 1., 0., 1., 0.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 0., 0.]])

สุ่มมาพิกัดนึง แบบ row_ column_, 5 คือสุ่มมาจาก 1-4, 3 คือสุ่มมาจาก 1-2

In [304]:
idx_choose = np.random.choice(5,3, replace=False)
idx_choose

array([0, 4, 3])

In [302]:
np_matrix_choose = np_matrix[idx_choose,:]
np_matrix_choose

array([[1., 0., 0., 0., 1.],
       [1., 0., 0., 1., 1.],
       [1., 0., 0., 0., 0.]])

# #Ex 2. Randomly create a matrix of size (10, 5) then randomly assign values of 0 and 1 to the last column of this matrix.

In [372]:
ex2 = np.random.rand(10,5)
ex2

array([[0.03881565, 0.01144413, 0.97399117, 0.64283042, 0.86859998],
       [0.11545875, 0.41912031, 0.10710936, 0.0787871 , 0.02365309],
       [0.10667878, 0.59523467, 0.39615379, 0.83185167, 0.7278828 ],
       [0.60719721, 0.85405173, 0.69668263, 0.76749647, 0.23379908],
       [0.25747151, 0.63390964, 0.75311922, 0.70552594, 0.43778604],
       [0.62445877, 0.46132239, 0.16590361, 0.96360307, 0.04933662],
       [0.05591502, 0.98882536, 0.17078026, 0.82542388, 0.76565388],
       [0.42929129, 0.73408537, 0.9576454 , 0.79091425, 0.55740759],
       [0.80709125, 0.35763855, 0.80320916, 0.47440147, 0.98944449],
       [0.16246233, 0.58315004, 0.33106034, 0.18104811, 0.84228008]])

สุ่ม 1-10 ในเมทริกซ์ขนาด 5x5

In [397]:
np_matrix = np.random.randint(5,size = (5,5))
np_matrix

array([[2, 4, 1, 2, 2],
       [0, 4, 3, 0, 2],
       [0, 2, 3, 0, 4],
       [2, 2, 2, 3, 1],
       [0, 1, 2, 1, 1]])

เช็คตำแหน่งว่าตำแหน่งไหนข้อมูลเป็นเลข 2 บ้าง

In [398]:
i,j = np.where(np_matrix == 2)
[(i[ii],j[ii]) for ii in range(len(i))]

[(0, 0), (0, 3), (0, 4), (1, 4), (2, 1), (3, 0), (3, 1), (3, 2), (4, 2)]

In [322]:
row,column = np.where(np_matrix==2)
[(row[i],column[i]) for i in range(len(row))]

[(1, 3), (2, 2), (2, 4)]

# #Ex 3. Why we cannot use this index ?

In [449]:
np_matrix

array([[2, 4, 1, 2, 2],
       [0, 4, 3, 0, 2],
       [0, 2, 3, 0, 4],
       [2, 2, 2, 3, 1],
       [0, 1, 2, 1, 1]])

In [453]:
idx = [1,2,3,4,5]
np_matrix[idx,:] 

IndexError: index 5 is out of bounds for axis 0 with size 5

ที่แสดงค่าไม่ได้เพราะ np_matrix มี 5 แถวคือ 0,1,2,3,4 แต่ค่าใน list idx มีเลข 5 คือไม่กรกหฏใน np_matrix

In [457]:
idx = [1,2,3,4,5]
idx_new = idx.remove(5)
np_matrix[idx_new,:] 

array([[[2, 4, 1, 2, 2],
        [0, 4, 3, 0, 2],
        [0, 2, 3, 0, 4],
        [2, 2, 2, 3, 1],
        [0, 1, 2, 1, 1]]])

In [340]:
rng = np.random.RandomState(0)
np_matrix = rng.randint(3 ,size=(3,3))
np_matrix

array([[0, 1, 0],
       [1, 1, 2],
       [0, 2, 0]])

ลบแถวที่ 2 และ 3 **0 จะเป็นแถว**

In [341]:
np_matrix = np.delete(np_matrix,[1,2],0)
np_matrix

array([[0, 1, 0]])

ลบคอลัมที่ 1 **1 จะเป็นคอลัม**

In [342]:
np_matrix = np.delete(np_matrix,[1],1)
np_matrix

array([[0, 0]])

In [345]:
rng = np.random.RandomState(0)
np_matrix = rng.randint(3 ,size=(3,3))
np_matrix

array([[0, 1, 0],
       [1, 1, 2],
       [0, 2, 0]])

เช็ค 2

In [346]:
a = np_matrix == 2
a

array([[False, False, False],
       [False, False,  True],
       [False,  True, False]])

In [348]:
np_matrix[a]=99
np_matrix

array([[ 0,  1,  0],
       [ 1,  1, 99],
       [ 0, 99,  0]])

# Ex 4. Randomly create a data matrix of 10 samples with 5 features. 

10 แถว 5 คอลัม แล้วแบ่งข้อมูลออกมาเป็น 2 กลุ่ม สร้าง vector ที่มีขนาด 10 และมีค่าเป็น 0,1 เท่านั้น 

In [434]:
rng = np.random.RandomState(0)
main_matrix = rng.randint(10 ,size=(10,5))
main_matrix

array([[5, 0, 3, 3, 7],
       [9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1],
       [6, 7, 7, 8, 1],
       [5, 9, 8, 9, 4],
       [3, 0, 3, 5, 0],
       [2, 3, 8, 1, 3],
       [3, 3, 7, 0, 1],
       [9, 9, 0, 4, 7],
       [3, 2, 7, 2, 0]])

In [435]:
rng = np.random.RandomState(0)
vertor = rng.randint(2, size=(10))
vertor

array([0, 1, 1, 0, 1, 1, 1, 1, 1, 1])

In [441]:
main_matrix[np.where(vertor==0)]

array([[5, 0, 3, 3, 7],
       [6, 7, 7, 8, 1]])

In [442]:
main_matrix[np.where(vertor==1)]

array([[9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1],
       [5, 9, 8, 9, 4],
       [3, 0, 3, 5, 0],
       [2, 3, 8, 1, 3],
       [3, 3, 7, 0, 1],
       [9, 9, 0, 4, 7],
       [3, 2, 7, 2, 0]])