In [277]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

**NumPy Array** Numpy คือชื่อของ library ที่ใช้ในการคำนวนทางคณิตศาสตร์ มีความสามารถในการจัดการกับอาเรย์หลายมิติและข้อมูลแบบเมทริกซ์

ใช้คำสั่ง import เข้ามาแล้วตั้งชื่อว่า np

In [278]:
import numpy as np

ถ้าไม่มีคำสั่งนั้นในเครื่อง ให้ใช้คำสั่ง

In [279]:
!pip install numpy

เช็คเวอร์ชั่น

In [280]:
np.__version__

'1.19.5'

การรู้เวอร์ชั่นจำเป็นมาก เพราะในการวิเคราะห์ข้อมูลส่วนใหญ่จะอ้างอิงจากข้อมูลผู้อื่น หากเวอร์ชั่นไม่ตรงกันก็จะ error

Vector or 1D Array

In [281]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [282]:
a[0]

1

ช่วง index [_:_]

In [283]:
a[0:5]

array([1, 2, 3, 4, 5])

ก่อนถึง index ที่ _

In [284]:
a[8]

9

In [285]:
a[:8]

array([1, 2, 3, 4, 5, 6, 7, 8])

ตั้งแต่ index ที่ _

In [286]:
a[3]

4

In [287]:
a[3:] 

array([ 4,  5,  6,  7,  8,  9, 10])

นับ index ย้อนหลัง [-_]

In [288]:
a[-2]

9

In [289]:
a[2:-3]

array([3, 4, 5, 6, 7])

In [290]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [291]:
a[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [292]:
sorted(a, reverse=True)

[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

จำนวนสมาชิกใน array

In [293]:
np.size(a)

10

แสดงเวกเตอร์

In [294]:
np.shape(a)

(10,)

a[2] = 3
จะได้ a[3] = 4

In [295]:
a[a[2]]

4

Matrix or 2D Array

In [296]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [297]:
np.shape(b)

(3, 3)

ตำแหน่งแรกคือ row (เรียง0.1,2,...) ตำแหน่งสองคือ column (เรียง0,1,2,...)

In [298]:
b[1,2]

6

In [299]:
b[1,:]

array([4, 5, 6])

In [300]:
b[:,-1]

array([3, 6, 9])

เปลี่ยนค่าใน array (column)

In [301]:
b[:,-1]=0
b

array([[1, 2, 0],
       [4, 5, 0],
       [7, 8, 0]])

In [302]:
b[:,-1]=[3,6,9]
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

เปลี่ยนค่า array (row)

In [303]:
b[1,:]=0
b

array([[1, 2, 3],
       [0, 0, 0],
       [7, 8, 9]])

In [304]:
b[1,:]=[4,5,6]
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

เพิ่มข้อมูลใน array 3 มิติยังไง

In [305]:
b = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

จำนวนสมาชิกใน array

In [306]:
np.size(b)

12

In [307]:
np.size(b,0)

4

เช็คมิติของ array

In [308]:
np.ndim(b)

2

In [309]:
c = np.zeros((2, 3, 4))
c

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [310]:
np.ndim(c)

3

**Data is Matrix** ใน array ข้อมูลหลายรูปแบบ str,int

In [311]:
student = np.array ([[622110186,'น้ำผึ้ง'],[622110174,'กิ๊ฟ'],[622110150,'พลอย']])
student

array([['622110186', 'น้ำผึ้ง'],
       ['622110174', 'กิ๊ฟ'],
       ['622110150', 'พลอย']], dtype='<U21')

In [312]:
np.array(student[:,0],dtype = int)

array([622110186, 622110174, 622110150])

In [313]:
np.array(student[:,0])

array(['622110186', '622110174', '622110150'], dtype='<U21')

**Special Type of Matrix**

สร้าง matrix 2x2 ที่มีค่าทั้งหมดเป็น 0 และ 1

In [314]:
c = np.zeros((2,2))
c

array([[0., 0.],
       [0., 0.]])

In [315]:
d = np.ones((2,2))
d

array([[1., 1.],
       [1., 1.]])

สร้าง matrix ที่กำหนดค่าข้างในเหมือนกันทุกตัว

In [316]:
e = np.full((2,2),8)
e

array([[8, 8],
       [8, 8]])

เลขหน้าคือ row เลขหลังคือ column

In [317]:
f = np.full((2,4),14)
f

array([[14, 14, 14, 14],
       [14, 14, 14, 14]])

In [318]:
g = np.ones((5,5))*4
g

array([[4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.]])

สร้าง Identity matrix (เมทริกซ์เอกลักษณ์)

In [319]:
g = np.eye(2)
g

array([[1., 0.],
       [0., 1.]])

คูณเมทริกซ์แค่ที่ตำแแหน่งมันตรงกันแบบ 0,0 ของ e คูณ 0,0 ของ g

In [320]:
e*g

array([[8., 0.],
       [0., 8.]])

สั่งให้ matrix คูณกันแบบไม่ต้องตำแหน่งตรงกัน เพราะหากเมทริกซ์ใดๆคูณเมทริกซ์เอกลักษณ์จะได้ตัวมันเอง

In [321]:
np.matmul(e,g)

array([[8., 8.],
       [8., 8.]])

คูณจำนวนเข้าเมทริกซ์ได้เลย

In [322]:
4*np.ones((2,2))

array([[4., 4.],
       [4., 4.]])

รากที่ 2 ของเมทริกซ์ 2x2 เมื่อค่าข้างในเป็น 4

In [323]:
np.sqrt(np.full((2,2),4))

array([[2., 2.],
       [2., 2.]])

มันขยะที่อยูู่ใน array แค่จองพื้นที่ไว้ก่อน 

In [324]:
np.empty((5,5))

array([[4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.]])

In [325]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

**Random**

สุ่มเลขระหว่าง 0-1

In [326]:
rng = np.random.RandomState(0)
rng.rand()

0.5488135039273248

สุ่มเลข 1-10

In [327]:
np.random.rand()*10

7.982791410961419

ถ้าทำ RandomState ไว้จะได้ค่าเดิมตลอด

In [328]:
rng.rand()*10

7.151893663724195

In [329]:
rng = np.random.RandomState(0)
np.round(rng.rand()*10)

5.0

random ตั้งแต่ 0-4 

In [330]:
np.random.randint(5)

4

In [331]:
[np.round(np.random.rand()*10) for item in range(10)]

[4.0, 6.0, 3.0, 2.0, 5.0, 10.0, 8.0, 5.0, 8.0, 7.0]

ตั้งให้การสุ่มทุกครั้งสุ่มได้ค่าเดิม

In [332]:
random1 = np.random.RandomState(0)
np_matrix = random1.randint(3, size = (5,5))
np_matrix

array([[0, 1, 0, 1, 1],
       [2, 0, 2, 0, 0],
       [0, 2, 1, 2, 2],
       [0, 1, 1, 1, 1],
       [0, 1, 0, 0, 1]])

สุ่มมาให้ข้อมูลไม่ซ้ำกันใส่ replace = False

In [333]:
a = [1,2,3,4,5,6,7,8,9,10]
np.random.choice(a,5, replace=False)

array([ 4,  3,  9,  6, 10])

In [334]:
np_matrix = np.round(np.random.rand(5,5))
np_matrix

array([[0., 1., 0., 1., 1.],
       [0., 1., 0., 1., 1.],
       [1., 1., 1., 1., 0.],
       [0., 1., 0., 1., 0.],
       [0., 0., 1., 1., 0.]])

สุ่มมาพิกัดนึง แบบ row_ column_, 5 คือสุ่มมาจาก 1-4, 3 คือสุ่มมาจาก 1-2

In [335]:
idx_choose = np.random.choice(5,3, replace=False)
idx_choose

array([3, 1, 4])

In [336]:
np_matrix_choose = np_matrix[idx_choose,:]
np_matrix_choose

array([[0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 1.],
       [0., 0., 1., 1., 0.]])

# #Ex 2. Randomly create a matrix of size (10, 5) then randomly assign values of 0 and 1 to the last column of this matrix.

In [337]:
ex2 = np.random.rand(10,5)
ex2[:,-1]=np.round(ex2[:,-1])
ex2

array([[0.31041762, 0.21130775, 0.88872298, 0.36318245, 1.        ],
       [0.47696921, 0.49693364, 0.67630189, 0.18007023, 0.        ],
       [0.88022156, 0.06365325, 0.83127628, 0.72725784, 0.        ],
       [0.06057673, 0.88703535, 0.166423  , 0.57522165, 1.        ],
       [0.11572768, 0.90662283, 0.97033742, 0.67653643, 0.        ],
       [0.40976386, 0.05613545, 0.30686943, 0.17003326, 1.        ],
       [0.58588504, 0.96782137, 0.43664646, 0.74100362, 0.        ],
       [0.2417608 , 0.25092886, 0.75642688, 0.78532177, 1.        ],
       [0.02725305, 0.18470149, 0.98218412, 0.82464661, 0.        ],
       [0.84572273, 0.59032623, 0.31295557, 0.06926271, 0.        ]])

สุ่ม 1-10 ในเมทริกซ์ขนาด 5x5

In [338]:
np_matrix = np.random.randint(5,size = (5,5))
np_matrix

array([[3, 4, 3, 1, 0],
       [4, 0, 3, 4, 1],
       [4, 3, 1, 0, 4],
       [2, 0, 2, 2, 0],
       [1, 4, 3, 0, 4]])

เช็คตำแหน่งว่าตำแหน่งไหนข้อมูลเป็นเลข 2 บ้าง

In [339]:
i,j = np.where(np_matrix == 2)
[(i[ii],j[ii]) for ii in range(len(i))]

[(3, 0), (3, 2), (3, 3)]

In [340]:
row,column = np.where(np_matrix==2)
[(row[i],column[i]) for i in range(len(row))]

[(3, 0), (3, 2), (3, 3)]

# #Ex 3. Why we cannot use this index ?

In [341]:
np_matrix

array([[3, 4, 3, 1, 0],
       [4, 0, 3, 4, 1],
       [4, 3, 1, 0, 4],
       [2, 0, 2, 2, 0],
       [1, 4, 3, 0, 4]])

ที่แสดงค่าไม่ได้เพราะ np_matrix มี 5 แถวคือ 0,1,2,3,4 แต่ค่าใน list idx มีเลข 5 คือไม่กรกหฏใน np_matrix

In [343]:
idx = [1,2,3,4,5]
idx_new = idx.remove(5)
np_matrix[idx_new,:] 

array([[[3, 4, 3, 1, 0],
        [4, 0, 3, 4, 1],
        [4, 3, 1, 0, 4],
        [2, 0, 2, 2, 0],
        [1, 4, 3, 0, 4]]])

In [ ]:
rng = np.random.RandomState(0)
np_matrix = rng.randint(3 ,size=(3,3))
np_matrix

ลบแถวที่ 2 และ 3 **0 จะเป็นแถว**

In [ ]:
np_matrix = np.delete(np_matrix,[1,2],0)
np_matrix

ลบคอลัมที่ 1 **1 จะเป็นคอลัม**

In [ ]:
np_matrix = np.delete(np_matrix,[1],1)
np_matrix

In [ ]:
rng = np.random.RandomState(0)
np_matrix = rng.randint(3 ,size=(3,3))
np_matrix

เช็ค 2

In [ ]:
a = np_matrix == 2
a

In [ ]:
np_matrix[a]=99
np_matrix

# Ex 4. Randomly create a data matrix of 10 samples with 5 features. 

10 แถว 5 คอลัม แล้วแบ่งข้อมูลออกมาเป็น 2 กลุ่ม สร้าง vector ที่มีขนาด 10 และมีค่าเป็น 0,1 เท่านั้น 

In [ ]:
rng = np.random.RandomState(0)
main_matrix = rng.randint(10 ,size=(10,5))
main_matrix

In [ ]:
rng = np.random.RandomState(0)
vertor = rng.randint(2, size=(10))
vertor

In [ ]:
main_matrix[np.where(vertor==0)]

In [ ]:
main_matrix[np.where(vertor==1)]